### ISSUE TITLE
Write Registers Issue

### ISSUE THREAD

**Issue by antoniobreton** [u-fire/ec-salinity-probe#1]
Hello 

I was looking into the code, and realize that there is an issue with the part where you save some data to the registers in the device. I saw in the library that you write data to some registers to the device, but in the device you don't save this data in any of the registers addressed. 

These are the variables you write to the device.
_write_register(EC_TEMPCOEF_REGISTER, tempCoefficient);
_write_register(EC_SOLUTION_REGISTER, solutionEC);

I found that you write this registers in some of the Methods, but in the device, in the part where it is suppose to save the data received into the EEPROM there is no way you can posibly do it. Correct me if I'm wrong but i think that in the part of the device where you save the received data should be.

//Save things when all 4 bytes fo the float have been received
if (reg_Position == (EC_TEMPCOEF_REGISTER + 3)) EEPROM.put(EC_TEMPCOEF_REGISTER, i2c_Register.tempCoef);
if (reg_Position == (EC_SOLUTION_REGISTER + 3)) EEPROM.put(EC_SOLUTION_REGISTER, i2c_Register.solutionEC);

I don't see any of those in the device code.

Hope you understand what I'm trying to point out.

Best regards.
Antonio Breton

antonio.breton.angulo@gmail.com

**Comment by justind000** [comment]
Hello Antonio,

You're right that they aren't saved. They are used more like temporary pieces of information though. The temperature coefficient might be a bit more permanent depending on use case, but the solution register value will change frequently and I assumed there was little use in saving those particular values. 

The firmware in another of my boards, a pH/ORP probe interface, includes methods to allow the user to read/write to the devices EEPROM. I haven't included them in the EC probe because I felt there was limited use for them and space is at a premium.

**Comment by antoniobreton** [comment]
Hello Justin.

Thanks for clarifying :), I think I got a little bit confused 

Best regards.
